---
title: "flight13"
output: html_notebook
---
```{r}
install.packages("tidyverse")
```


```{r}
install.packages("nycflights13")
```
```{r}
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
suppressPackageStartupMessages(library(nycflights13))
```
```{r}
flights
```


```{r}
Q1 <- flights%>%
  group_by(carrier)%>%
  summarise(dis_mean =round(mean(distance), 2))%>%
  filter(carrier %in% c("AA", "EV", "FL"))%>%
  as.data.frame()
Q1

```
```{r}
Q2 <- flights %>% 
  select(flight, month)%>%
  #group_by(month)%>%
  summarise(highest = max(flight))
Q2

```
```{r}
Q3 <- flights%>%
  group_by(origin, dest)%>%
  summarise(mean_distance = min(distance))%>%
  arrange(desc(mean_distance))
  tail(5)%>%
  as.data.frame()
Q3
```
```{r}
Q4 <- flights%>%
  group_by(origin, month, day)%>%
  summarise(dis_mean = mean(distance), .groups = 'drop')%>%
  arrange(desc(dis_mean))%>%
  filter(origin == "JFK")%>%
  head(5)%>%
  as.data.frame()
Q4
```


```{r}
Q5 <- flights%>%
  group_by(dest)%>%
  filter(!is.na(arr_delay))%>%
  summarise(max_arr_delay = max(arr_delay))%>%
  filter(dest == "BOS" | dest == "ATL")
Q5
```




